architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    mixin {
        defaultRefmapName = "what_lurks_between.refmap.json"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    compileOnly "me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}"

    compileOnly "curse.maven:veroxlib-1502883:8431322"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modImplementation "mod.azure.azurelib:azurelib-common-${rootProject.azurelib_version}"
    compileOnly "com.github.glitchfiend:TerraBlender-common:${terrablender_version}"

}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

processResources {
    tasks.withType(AbstractCopyTask).configureEach {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
        exclude '.cache/**'
    }
}